### ISSUE TITLE
Empty expand 

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#122]
`echo $DONT salut` doit rendre
`salut` et pas ` salut`

**Comment by aascedu** [comment]
Ca c'est ton echo qui fait mal le boulot, moi j'expand $DONT ca me donne "" en char, et le token d'apres c'est "salut" donc a la fin de mon parsing t'as :
-echo (CMD)
-"" (ARG)
-"salut". (ARG)

mtn si ton echo affiche une chaine vide je sais pas comment le regler.

**Comment by aascedu** [comment]
Apres je peux jeter un oeil mais le problem vient du built-in pas du parsing.

**Comment by maplepy** [comment]
`@maplepy ➜ /workspaces/minishell (exec) $ echo $DONT salut`
`salut`


`@maplepy ➜ /workspaces/minishell (exec) $ echo "$DONT" salut`
 `salut`

**Comment by aascedu** [comment]
Yes, j'essaie de corriger alors, j'ai vu ou c'etait, mais ca fout le bordel pour le reste du parsing ...

**Comment by maplepy** [comment]
force

**Comment by aascedu** [comment]
DONE Jai fix un peu echo et un peu le parsing mdr

**Comment by aascedu** [comment]
Je vais essayé de faire ca en mieux pour supprimer de la liste chainé les elements NULL.
Mais c'est pas facile !

**Comment by aascedu** [comment]
okay no problems !

**Comment by aascedu** [comment]
YESSIRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRSKI

**Comment by maplepy** [comment]
euuuuh

`minishell> echo "" lol`
`lol`

**Comment by maplepy** [comment]
`minishell> echo " " lol`
`  lol` <- 2 espaces a la place d'un

**Comment by maplepy** [comment]
j'avais revert ta PR sur tes changements d'echo t'avais pull la master ou pas?

**Comment by maplepy** [comment]
mauvaise nouvelle

**Comment by maplepy** [comment]
tes changements on casse des fonctions parce que `""` est considere comme rien alors que ca devrait etre une string vide, pas nulle

**Comment by maplepy** [comment]
- `ls ""` cherche un fichier qui est literallement vide de nom
- `ls " "` cherche un fichier espace
- `ls` ne cherche rien et donne tous les fichiers du dossier courant
- `ls $BLABLA` quand `BLABLA` n'existe pas, pareil que le cas precedent

**Comment by maplepy** [comment]
fais bien des tests avant de PR

**Comment by aascedu** [comment]
Bas attends y'avait pas besoin de revert la frerot, je vais fix ca...

**Comment by maplepy** [comment]
pas de souci tu peux repush dans tous les cas avec le code qui marche

**Comment by aascedu** [comment]
A tester plus en profondeur mais je pense que ca fonctionne bien.
