### ISSUE TITLE
Expand function

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#123]
`export test="echo lol"` should display `lol` instead of `echo lol : command not found` -> expand before split in tokens

**Comment by aascedu** [comment]
Pour ce problème, je ne vois pas du tout comment le gerer. Je crois que la conception de mon parsing ne permet pas de faire ca, enfaite il fait les tokens puis il expand. Donc si tu as un expand qui contient la commande, il va d'abord couper autour de la variable, puis ensuite dire : ca c'est la commande et ensuite expand, sauf qu'en faisant ca, il s'en fou si y'a "echo          lol" dans l'expand, pour lui ce sera juste une commande....
A voir si je peux regler, c'est un test assez batard je trouve mais ce serait bien de l'avoir.

**Comment by maplepy** [comment]
oui parce que c'est pas mal teste de ce que j'ai vu

**Comment by aascedu** [comment]
Il faudrait faire les tests mais je pense que c'est bon.
