### ISSUE TITLE
CTRL+C in timed function

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#124]
`sleep 4` with CTRL+C prints `minishell>` twice

**Comment by aascedu** [comment]
Ca c'est les signaux dans les fork quon a pas encore géré.

**Comment by maplepy** [comment]
tu fais ca demain du coup?

**Comment by aascedu** [comment]
Oui on reverra ensemble pour voir ou implementer le code pour gerer cette erreur. Car il faut que ton code a toi soit fini je crois pour gerer. J'en suis pas sur....

**Comment by maplepy** [comment]
oui oui sinon ca bloquerais l'input
