### ISSUE TITLE
CTRL+`\`

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#125]
doing `cat` and pressing `CTRL+\` should do
`^\Quit (core dumped)` with exit code `131`

**Comment by aascedu** [comment]
Gérer ctrl-C, ctrl-D et ctrl-\ qui doivent fonctionner comme dans bash.
• En mode interactif :
◦ ctrl-C affiche un nouveau prompt sur une nouvelle ligne.
◦ ctrl-D quitte le shell.
◦ ctrl-\ ne fait rien.

Soit je comprends mal soit il faut pas faire ca si ? Ou alors bash dans un cat te fait Quit Core dumped ?

**Comment by maplepy** [comment]
`cat`, `wc` etc.. 
toutes les fonctions qui sont interactive en gros
