### ISSUE TITLE
SIGSEV on undefined var

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#140]
![image](https://github.com/42-tronc/minishell/assets/28269333/1ae50aef-a9fa-466c-bf9e-350c7df5e64c)

**Comment by maplepy** [comment]
jsp si c'est moi ou toi qui doit fix ca @aascedu

**Comment by aascedu** [comment]
je vais regarder, c’est peut être moi en vrai. tu peux pas mettre fsnanitize pour voir où ça segfault ?

**Comment by maplepy** [comment]
si je vais faire ca juste apres je revise un peu printf et gnl pour lexam

**Comment by aascedu** [comment]
Fixed.
