### ISSUE TITLE
Wrong exit code on error

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#141]
![image](https://github.com/42-tronc/minishell/assets/28269333/e8d1bc0d-b49c-4ed2-bb04-ce2b809ec376)

**Comment by aascedu** [comment]
ah oui on gère pas j’avais pas pensé, je vais corriger ça d’ici peu

**Comment by aascedu** [comment]
A verifier je pense
mais j'ai change deux trois trucs
