### ISSUE TITLE
Here_doc close minishell signals

### ISSUE THREAD

**Issue by aascedu** [42-tronc/minishell#166]
Attention a ne pas close l'exec si ctrl d dans un here_doc

**Comment by maplepy** [comment]
ne pas close l'exec?

**Comment by aascedu** [comment]
l’exécution du programme minishell

**Comment by maplepy** [comment]
je close pas l'exec avec un ctrl d

**Comment by aascedu** [comment]
je te parle de moi.

**Comment by maplepy** [comment]
aah oui ok, je pensais que l'issue etait pour moi
