### ISSUE TITLE
Expand

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#209]
`minishell> echo $SHELL`
`/usr/bin/fish`

`minishell> echo e$SHELL`
`SHELL`

# Bash
`echo $SHELL`
`/usr/bin/fish`

`echo e$SHELL`
`e/usr/bin/fish`

**Comment by aascedu** [comment]
Do you have les cramptes ? Tu avais fait du debug juste avant aussi normal y'a une erreur tu dois avoir un malloc a NULL !
![Screenshot from 2023-08-10 08-41-54](https://github.com/42-tronc/minishell/assets/109480420/8dfa445e-38b4-48fe-abfb-24b446ca0b6e)
![Screenshot from 2023-08-10 08-42-11](https://github.com/42-tronc/minishell/assets/109480420/bfdca0c8-d9f5-48fd-b944-049e8ab0a148)

**Comment by maplepy** [comment]
quoi coubeh? oui c'est quand ya un malloc a null, sinon ca marche bien. faut juste rajouter un msg et peut etre pas faire la commande ou quelque chose comme ca
