### ISSUE TITLE
CTRL+C closes the program

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#56]
`CTRL+C` should not close the program but only the function

**Comment by maplepy** [comment]
c pas regle ca si?

**Comment by aascedu** [comment]
je suis entrain de bosser dessus la mais tkt pas besoin de laisser une issue

**Comment by maplepy** [comment]
niquel, par contre apparemment thomas a trouve des pb avec les signaux jcrois

**Comment by aascedu** [comment]
il me montre demain si tu veux
